apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-miker-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chekdata/ops-bootstrap.git
    targetRevision: main
    path: templates/k8s/kustomize/frontend-miker-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: miker-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true


