# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chek_dataframe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chek_dataframe.proto',
  package='chek',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x63hek_dataframe.proto\x12\x04\x63hek\"\x86\x01\n\x03IMU\x12\r\n\x05x_acc\x18\x01 \x01(\x02\x12\r\n\x05y_acc\x18\x02 \x01(\x02\x12\r\n\x05z_acc\x18\x03 \x01(\x02\x12\r\n\x05x_ang\x18\x04 \x01(\x02\x12\r\n\x05y_ang\x18\x05 \x01(\x02\x12\r\n\x05z_ang\x18\x06 \x01(\x02\x12\x0b\n\x03x_w\x18\x07 \x01(\x02\x12\x0b\n\x03y_w\x18\x08 \x01(\x02\x12\x0b\n\x03z_w\x18\t \x01(\x02\"<\n\x03GPS\x12\x0b\n\x03lon\x18\x01 \x01(\x02\x12\x0b\n\x03lat\x18\x02 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\x04\x12\r\n\x05speed\x18\x04 \x01(\x05\"W\n\x03\x42ox\x12\n\n\x02x0\x18\x01 \x01(\r\x12\n\n\x02y0\x18\x02 \x01(\r\x12\n\n\x02x1\x18\x03 \x01(\r\x12\n\n\x02y1\x18\x04 \x01(\r\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"I\n\x03HMI\x12\x1d\n\ndetections\x18\x01 \x03(\x0b\x32\t.chek.Box\x12#\n\x10speed_detections\x18\x02 \x03(\x0b\x32\t.chek.Box\"5\n\x05Scene\x12\x0c\n\x04road\x18\x01 \x01(\t\x12\x0f\n\x07weather\x18\x02 \x01(\t\x12\r\n\x05light\x18\x03 \x01(\t\"(\n\x07Vehicle\x12\x1d\n\ndetections\x18\x01 \x03(\x0b\x32\t.chek.Box\"\xcf\x01\n\rChekDataFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x16\n\x03imu\x18\x03 \x01(\x0b\x32\t.chek.IMU\x12\x16\n\x03gps\x18\x04 \x01(\x0b\x32\t.chek.GPS\x12\x15\n\rkeyboard_flag\x18\x05 \x01(\t\x12\x16\n\x03hmi\x18\x06 \x01(\x0b\x32\t.chek.HMI\x12\x1a\n\x05scene\x18\x07 \x01(\x0b\x32\x0b.chek.Scene\x12\x1e\n\x07vehicle\x18\x08 \x01(\x0b\x32\r.chek.Vehicleb\x06proto3'
)




_IMU = _descriptor.Descriptor(
  name='IMU',
  full_name='chek.IMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_acc', full_name='chek.IMU.x_acc', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_acc', full_name='chek.IMU.y_acc', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_acc', full_name='chek.IMU.z_acc', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_ang', full_name='chek.IMU.x_ang', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_ang', full_name='chek.IMU.y_ang', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_ang', full_name='chek.IMU.z_ang', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_w', full_name='chek.IMU.x_w', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_w', full_name='chek.IMU.y_w', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_w', full_name='chek.IMU.z_w', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=165,
)


_GPS = _descriptor.Descriptor(
  name='GPS',
  full_name='chek.GPS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lon', full_name='chek.GPS.lon', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='chek.GPS.lat', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='chek.GPS.date', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed', full_name='chek.GPS.speed', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=227,
)


_BOX = _descriptor.Descriptor(
  name='Box',
  full_name='chek.Box',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x0', full_name='chek.Box.x0', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y0', full_name='chek.Box.y0', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x1', full_name='chek.Box.x1', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y1', full_name='chek.Box.y1', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='chek.Box.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='chek.Box.confidence', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=316,
)


_HMI = _descriptor.Descriptor(
  name='HMI',
  full_name='chek.HMI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='chek.HMI.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_detections', full_name='chek.HMI.speed_detections', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=391,
)


_SCENE = _descriptor.Descriptor(
  name='Scene',
  full_name='chek.Scene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='road', full_name='chek.Scene.road', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weather', full_name='chek.Scene.weather', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='light', full_name='chek.Scene.light', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=446,
)


_VEHICLE = _descriptor.Descriptor(
  name='Vehicle',
  full_name='chek.Vehicle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='chek.Vehicle.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=488,
)


_CHEKDATAFRAME = _descriptor.Descriptor(
  name='ChekDataFrame',
  full_name='chek.ChekDataFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='chek.ChekDataFrame.frame_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='chek.ChekDataFrame.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu', full_name='chek.ChekDataFrame.imu', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gps', full_name='chek.ChekDataFrame.gps', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyboard_flag', full_name='chek.ChekDataFrame.keyboard_flag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hmi', full_name='chek.ChekDataFrame.hmi', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scene', full_name='chek.ChekDataFrame.scene', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='chek.ChekDataFrame.vehicle', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=698,
)

_HMI.fields_by_name['detections'].message_type = _BOX
_HMI.fields_by_name['speed_detections'].message_type = _BOX
_VEHICLE.fields_by_name['detections'].message_type = _BOX
_CHEKDATAFRAME.fields_by_name['imu'].message_type = _IMU
_CHEKDATAFRAME.fields_by_name['gps'].message_type = _GPS
_CHEKDATAFRAME.fields_by_name['hmi'].message_type = _HMI
_CHEKDATAFRAME.fields_by_name['scene'].message_type = _SCENE
_CHEKDATAFRAME.fields_by_name['vehicle'].message_type = _VEHICLE
DESCRIPTOR.message_types_by_name['IMU'] = _IMU
DESCRIPTOR.message_types_by_name['GPS'] = _GPS
DESCRIPTOR.message_types_by_name['Box'] = _BOX
DESCRIPTOR.message_types_by_name['HMI'] = _HMI
DESCRIPTOR.message_types_by_name['Scene'] = _SCENE
DESCRIPTOR.message_types_by_name['Vehicle'] = _VEHICLE
DESCRIPTOR.message_types_by_name['ChekDataFrame'] = _CHEKDATAFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMU = _reflection.GeneratedProtocolMessageType('IMU', (_message.Message,), {
  'DESCRIPTOR' : _IMU,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.IMU)
  })
_sym_db.RegisterMessage(IMU)

GPS = _reflection.GeneratedProtocolMessageType('GPS', (_message.Message,), {
  'DESCRIPTOR' : _GPS,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.GPS)
  })
_sym_db.RegisterMessage(GPS)

Box = _reflection.GeneratedProtocolMessageType('Box', (_message.Message,), {
  'DESCRIPTOR' : _BOX,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.Box)
  })
_sym_db.RegisterMessage(Box)

HMI = _reflection.GeneratedProtocolMessageType('HMI', (_message.Message,), {
  'DESCRIPTOR' : _HMI,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.HMI)
  })
_sym_db.RegisterMessage(HMI)

Scene = _reflection.GeneratedProtocolMessageType('Scene', (_message.Message,), {
  'DESCRIPTOR' : _SCENE,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.Scene)
  })
_sym_db.RegisterMessage(Scene)

Vehicle = _reflection.GeneratedProtocolMessageType('Vehicle', (_message.Message,), {
  'DESCRIPTOR' : _VEHICLE,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.Vehicle)
  })
_sym_db.RegisterMessage(Vehicle)

ChekDataFrame = _reflection.GeneratedProtocolMessageType('ChekDataFrame', (_message.Message,), {
  'DESCRIPTOR' : _CHEKDATAFRAME,
  '__module__' : 'chek_dataframe_pb2'
  # @@protoc_insertion_point(class_scope:chek.ChekDataFrame)
  })
_sym_db.RegisterMessage(ChekDataFrame)


# @@protoc_insertion_point(module_scope)
