# Generated by Django 5.0.6 on 2024-07-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_config',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='model_config id')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='model_config model')),
                ('hardware_config_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='model_config hardware_config_version')),
                ('software_config_version', models.CharField(blank=True, max_length=2000, null=True, verbose_name='model_config software_config_version')),
            ],
        ),
    ]
