# Generated by Django 5.0.6 on 2024-07-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_model_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='model_config',
        ),
    ]
