# Generated by Django 5.0.6 on 2024-07-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_model_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_config',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='model_config brand'),
        ),
    ]
