# Generated by Django 5.0.6 on 2024-07-15 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_model_config_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='model_config_app_update',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='model_config_app_update id')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_brand', models.CharField(editable=False, max_length=100, verbose_name='新建品牌名')),
                ('created_model', models.CharField(editable=False, max_length=100, verbose_name='新建车型')),
                ('created_hardware_config_version', models.CharField(editable=False, max_length=100, verbose_name='新建硬件版本')),
                ('created_software_config_version', models.CharField(editable=False, max_length=100, verbose_name='新建软件版本')),
                ('check_status', models.CharField(editable=False, max_length=100, verbose_name='审核状态')),
                ('check_manager', models.CharField(editable=False, max_length=100, verbose_name='审核人员')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_config_app_update',
            },
        ),
    ]
