# Generated by Django 5.0.6 on 2024-07-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_model_config_app_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_config_app_update',
            old_name='user_id',
            new_name='user',
        ),
    ]
