# Generated by Django 5.0.6 on 2024-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_user_id_model_config_app_update_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_config_app_update',
            name='created_brand',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='新建品牌名'),
        ),
        migrations.AlterField(
            model_name='model_config_app_update',
            name='created_hardware_config_version',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='新建硬件版本'),
        ),
        migrations.AlterField(
            model_name='model_config_app_update',
            name='created_model',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='新建车型'),
        ),
        migrations.AlterField(
            model_name='model_config_app_update',
            name='created_software_config_version',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='新建软件版本'),
        ),
        migrations.AlterField(
            model_name='model_config_app_update',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
