# Generated by Django 5.0.6 on 2024-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_model_config_app_update_created_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_config_app_update',
            name='check_manager',
            field=models.CharField(max_length=100, verbose_name='审核人员'),
        ),
        migrations.AlterField(
            model_name='model_config_app_update',
            name='check_status',
            field=models.CharField(max_length=100, verbose_name='审核状态'),
        ),
    ]
