# Generated by Django 5.0.6 on 2024-08-30 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_model_config_app_update_check_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_config',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID'),
        ),
    ]
