name: vehicle-model-service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/ci-docker-ssh-deploy.yml
    with:
      image: your-org/vehicle-model-service
      container_name: vehicle-model-service
      deploy_ports: 8081:8081
      env_vars: NODE_ENV=production
    secrets: inherit


