#!/usr/bin/env python3
"""
根据 raw-aiService.*.json 导出“今天 11:00–23:00”的 AI 聊天提示到一个 Markdown 文件。

数据来源：
- .specstory/history/raw-aiService.generations.json
- .specstory/history/raw-aiService.prompts.json

说明：
- generations 里包含 unixMs，可精确按时间筛选；
- prompts 里没有时间戳，只能作为“附录”全部列出。
"""

import json
import os
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HISTORY_DIR = os.path.join(REPO_ROOT, ".specstory", "history")
LOCAL_OUT_DIR = os.path.join(REPO_ROOT, "_local")

GENERATIONS_PATH = os.path.join(HISTORY_DIR, "raw-aiService.generations.json")
PROMPTS_PATH = os.path.join(HISTORY_DIR, "raw-aiService.prompts.json")


LOCAL_TZ = timezone(timedelta(hours=8))  # 近似认为是北京时间


def load_json_array(path: str) -> List[Dict[str, Any]]:
    if not os.path.exists(path):
        return []
    with open(path, "r", encoding="utf-8") as f:
        text = f.read().strip()
        if not text:
            return []
        data = json.loads(text)
        if isinstance(data, list):
            return data
        return []


def main() -> None:
    os.makedirs(LOCAL_OUT_DIR, exist_ok=True)

    generations = load_json_array(GENERATIONS_PATH)
    prompts = load_json_array(PROMPTS_PATH)

    now_local = datetime.now(LOCAL_TZ)
    today = now_local.date()
    start_dt = datetime(today.year, today.month, today.day, 11, 0, 0, tzinfo=LOCAL_TZ)
    end_dt = datetime(today.year, today.month, today.day, 23, 0, 0, tzinfo=LOCAL_TZ)

    # 过滤今天 11:00–23:00 的 generations
    window_generations: List[Dict[str, Any]] = []
    for g in generations:
        ts_ms = g.get("unixMs")
        if not isinstance(ts_ms, (int, float)):
            continue
        dt_utc = datetime.fromtimestamp(ts_ms / 1000.0, tz=timezone.utc)
        dt_local = dt_utc.astimezone(LOCAL_TZ)
        if start_dt <= dt_local <= end_dt:
            g_copy = dict(g)
            g_copy["_dt_local"] = dt_local
            window_generations.append(g_copy)

    window_generations.sort(key=lambda x: x["_dt_local"])

    # 生成 Markdown 内容
    lines: List[str] = []
    lines.append("<!-- Generated by export_ai_chat_today_window.py -->")
    lines.append("")
    lines.append(
        f"**时间范围（本地时区）**：{start_dt.strftime('%Y-%m-%d %H:%M')} ~ {end_dt.strftime('%Y-%m-%d %H:%M')}"
    )
    lines.append("")
    lines.append("### 从 aiService.generations 提取的提示")
    lines.append("")

    if not window_generations:
        lines.append("- **提示**：该时间段内未找到任何 generations 记录。")
    else:
        for idx, g in enumerate(window_generations, start=1):
            dt_str = g["_dt_local"].strftime("%Y-%m-%d %H:%M:%S")
            uuid = g.get("generationUUID", "")
            text = (g.get("textDescription") or "").strip()
            header = f"- **消息 {idx}** · {dt_str}"
            if uuid:
                header += f" · UUID: `{uuid}`"
            lines.append(header)
            lines.append("")
            lines.append("```text")
            lines.append(text)
            lines.append("```")
            lines.append("")

    lines.append("")
    lines.append("### 来自 aiService.prompts 的命令文本（该结构无时间戳，无法按时间精确筛选）")
    lines.append("")

    if not prompts:
        lines.append("- **提示**：未找到 prompts 记录。")
    else:
        for idx, p in enumerate(prompts, start=1):
            text = (p.get("text") or "").strip()
            cmd_type = p.get("commandType")
            header = f"- **Prompt {idx}**"
            if cmd_type is not None:
                header += f" · commandType={cmd_type}"
            lines.append(header)
            lines.append("")
            lines.append("```text")
            lines.append(text)
            lines.append("```")
            lines.append("")

    out_name = f"ai-chat-{today.strftime('%Y%m%d')}-1100-2300.md"
    out_path = os.path.join(LOCAL_OUT_DIR, out_name)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()


