FROM ghcr.io/kubernetes-sigs/nfs-subdir-external-provisioner:v4.0.2

LABEL org.opencontainers.image.title="nfs-subdir-external-provisioner"
LABEL org.opencontainers.image.version="v4.0.2"
LABEL org.opencontainers.image.source="https://github.com/chekdata/ops-bootstrap"





