# Generated by Django 5.0.6 on 2024-07-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='用户名')),
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='微信开放平台ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='user_pics/', verbose_name='个人头像')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='手机号')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('signature', models.TextField(blank=True, null=True, verbose_name='个人签名')),
                ('app_software_config_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='App版本号')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'user',
            },
        ),
    ]
