# Generated by Django 5.0.6 on 2024-07-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_id',
            new_name='id',
        ),
    ]
