# Generated by Django 5.0.6 on 2024-07-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
