# Generated by Django 5.0.6 on 2024-07-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_name_alter_user_password_smsverification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smsverification',
            table='SMS_verify',
        ),
    ]
