# Generated by Django 5.0.6 on 2024-07-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_smsverification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.IntegerField(max_length=6),
        ),
    ]
