# Generated by Django 5.0.6 on 2024-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_smsverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
