# Generated by Django 5.0.6 on 2024-07-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_smsverification_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsverification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
