# Generated by Django 5.0.6 on 2024-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_user_id_smsverification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='smsverification',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
