# Generated by Django 5.0.6 on 2024-07-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_smsverification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='model_config',
            field=models.JSONField(blank=True, null=True, verbose_name='车型配置数据'),
        ),
    ]
