# Generated by Django 5.1.6 on 2025-02-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_name_alter_user_password'),
        ('accounts', '0017_user_model_config'),
    ]

    operations = [
    ]
