"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e=b(uxht1ny%5*y5ihjxgg(ev326p(lrney+yz3&xlk+by*mvv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "*"
]
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'data',
    'common_task',
    'drf_yasg2',
    'social_django',
    'corsheaders',
    'drf_yasg',
    'drf_spectacular',
]

ASYNC_MODE = 'django'  # 不知道啥用
ASGI_APPLICATION = 'myproject.asgi.application'

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
USE_TZ = True  # 确保使用时区
TIME_ZONE = 'Asia/Shanghai'  # 设置项目时区（根据实际需求调整）

# debug
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'app_project',
        'USER': 'developer',
        'PASSWORD': '6vIODsjoYlYLuSC6',
        'HOST': '180.184.75.25',
        # 'HOST': '62.234.57.136',
        # 'HOST': '1.95.39.248',
        'PORT': '3306',
         'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='-8:00'",  # 设置时区为东八区
            'charset': 'utf8mb4',  # 添加字符集配置，支持4字节emoji等特殊字符
        },
    },
    'core_user': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'core_user',
        'USER': 'developer',
        'PASSWORD': '6vIODsjoYlYLuSC6',
        'HOST': '180.184.75.25',
        # 'HOST': '62.234.57.136',
        # 'HOST': '1.95.39.248',
        'PORT': '3306',
         'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', time_zone='-8:00'",  # 设置时区为东八区
            'charset': 'utf8mb4',  # 添加字符集配置，支持4字节emoji等特殊字符
        },
    }
}


# DATABASE_ROUTERS = ['myproject.routers.DatabaseRouter']
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'API接口文档',
    'DESCRIPTION': '项目详情介绍',
    'VERSION': '1.0.0',
    'COMPONENT_SPLIT_REQUEST': True,  # 将请求体参数分离为独立的组件
    # 可以在这里添加更多 drf-spectacular 的设置
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# AUTHENTICATION_BACKENDS = (
#     'social_core.backends.weixin.WeixinOAuth2',
# )

SOCIAL_AUTH_WEIXIN_KEY = 'wxe24cb2373dae28a1'
SOCIAL_AUTH_WEIXIN_SECRET = 'e08ac201c7fa17bb812e406e0ddbf1f0'

AUTH_USER_MODEL = 'accounts.User'
os.environ['DJANGO_ALLOW_ASYNC_UNSAFE'] = 'true'
AUTHENTICATION_BACKENDS = ['path.to.UserIDAuthBackend']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },

    },
    'handlers': {
        'console': {  # 添加 console handler
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file','console'],
            'level' : 'INFO',
            'propagate': True,
        },
        'common_task': {  # 添加你的应用日志器
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'accounts': {  # 添加账户应用日志器
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'data': {  # 添加数据应用日志器
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}

TIME_THRE = 300
VIDEO_ON_DEMAND = "/tos/video-on-demand/"
RECORD_UPLOAD_TOS_SUCCESS = "上传成功"
RECORD_UPLOAD_TOS_FAILED = "上传失败"
RECORD_UPLOAD_TOS_ING = "上传中"
RECORD_UPLOAD_TOS_FILE_MISSING = "文件丢失"
JOURNEY_STATUS_ING = "行程生成中"
JOURNEY_STATUS_FAILED = "异常退出待确认"
JOURNEY_STATUS_SUCCESS = "正常"

# 之家数据分发域名
DATA_DISTRIBUTION = "autohome-report.chekkk.com"