FROM registry.k8s.io/pause:3.6

LABEL org.opencontainers.image.title="pause"
LABEL org.opencontainers.image.version="3.6"
LABEL org.opencontainers.image.source="https://github.com/chekdata/ops-bootstrap"






