# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chek_message_pb2 as chek__message__pb2


class SaasChekMessageHandleRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.saveResource = channel.unary_unary(
                '/com.vehicle.saas.proto.SaasChekMessageHandleR/saveResource',
                request_serializer=chek__message__pb2.ChekMessage.SerializeToString,
                response_deserializer=chek__message__pb2.resultR.FromString,
                )


class SaasChekMessageHandleRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def saveResource(self, request, context):
        """保存资源信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaasChekMessageHandleRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'saveResource': grpc.unary_unary_rpc_method_handler(
                    servicer.saveResource,
                    request_deserializer=chek__message__pb2.ChekMessage.FromString,
                    response_serializer=chek__message__pb2.resultR.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.vehicle.saas.proto.SaasChekMessageHandleR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SaasChekMessageHandleR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def saveResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.vehicle.saas.proto.SaasChekMessageHandleR/saveResource',
            chek__message__pb2.ChekMessage.SerializeToString,
            chek__message__pb2.resultR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
