name: ci-docker-vecr

on:
  workflow_dispatch:
    inputs:
      image:
        description: Image repo path under VECR (e.g. prod/miker-web)
        required: true
        default: prod/miker-web
      tag:
        description: Image tag
        required: true
        default: v0.1.0
  push:
    branches: [ main, dev, staging ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm i -g pnpm@9
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -w lint || true
      - name: Test
        run: pnpm -w test || true
      - name: Preflight DNS
        run: |
          nslookup ${{ secrets.VECR_REGISTRY }} || true
          getent hosts ${{ secrets.VECR_REGISTRY }} || true
      - name: Login VECR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.VECR_REGISTRY }}
          username: ${{ secrets.VECR_USER }}
          password: ${{ secrets.VECR_PASS }}
      - name: Build and push
        env:
          REGISTRY: ${{ secrets.VECR_REGISTRY }}
          IMAGE: ${{ github.event.inputs.image || 'devops/example' }}
          TAG: ${{ github.event.inputs.tag || github.sha }}
        run: |
          docker build -t "$REGISTRY/$IMAGE:$TAG" .
          docker push "$REGISTRY/$IMAGE:$TAG"


