# Generated by Django 5.1.7 on 2025-04-17 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),  # 确保依赖于accounts应用的迁移
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('car_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_merging', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('merged_csv_path', models.CharField(blank=True, max_length=255, null=True)),
                ('merged_det_path', models.CharField(blank=True, max_length=255, null=True)),
                ('hardware_version', models.CharField(blank=True, max_length=64, null=True)),
                ('software_version', models.CharField(blank=True, max_length=64, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Trip',
            },
        ),
        migrations.CreateModel(
            name='analysis_data_app',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('model', models.CharField(editable=False, max_length=255, null=True, verbose_name='用户使用车型')),
                ('intervention', models.IntegerField(blank=True, default=0, null=True, verbose_name='接管次数')),
                ('intervention_risk', models.IntegerField(blank=True, default=0, null=True, verbose_name='危险接管次数')),
                ('mpi', models.FloatField(blank=True, default=0.0, null=True, verbose_name='接管里程')),
                ('mpi_risk', models.FloatField(blank=True, default=0.0, null=True, verbose_name='危险接管里程')),
                ('total_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='总里程')),
                ('noa_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA总里程')),
                ('lcc_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='LCC总里程')),
                ('noa_lcc_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA LCC总里程')),
                ('standby_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='人类驾驶里程')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'analysis_data_app',
            },
        ),
        migrations.CreateModel(
            name='tos_csv_app',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tos_file_path', models.CharField(editable=False, max_length=2000, verbose_name='tos存储路径')),
                ('tos_file_type', models.CharField(editable=False, max_length=2000, verbose_name='tos存储文件类型 inference/analysis')),
                ('approved_status', models.IntegerField(default=0, verbose_name='审核状态：0 未审核， 1 审核通过 2 审核不通过')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'tos_csv_app',
            },
        ),
        migrations.CreateModel(
            name='ChunkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('file_path', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('car_name', models.CharField(max_length=100)),
                ('hardware_version', models.CharField(blank=True, max_length=64, null=True)),
                ('software_version', models.CharField(blank=True, max_length=64, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='common_task.trip')),
            ],
            options={
                'db_table': 'ChunkFile',
                'unique_together': {('trip', 'chunk_index', 'file_type')},
            },
        ),
    ]
