# Generated by Django 5.0.6 on 2024-07-10 07:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysis_data_app',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('user_id', models.CharField(editable=False, max_length=100, verbose_name='用户ID')),
            ],
            options={
                'db_table': 'analysis_data_app',
            },
        ),
    ]
