# Generated by Django 5.1.7 on 2025-07-09 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='HotBrandVehicle',
        #     fields=[
        #         ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
        #         ('brand_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌类型')),
        #         ('cover_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图片')),
        #         ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='车型')),
        #         ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
        #         ('power_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='动力类型')),
        #         ('vehicle_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='车辆类型')),
        #         ('hardware_config_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='硬件配置版本')),
        #         ('market_price_max', models.FloatField(blank=True, null=True, verbose_name='市场价格最大值')),
        #         ('market_price_min', models.FloatField(blank=True, null=True, verbose_name='市场价格最小值')),
        #         ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='创建日期')),
        #         ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
        #     ],
        #     options={
        #         'db_table': 'hot_brand_vehicle',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Trip',
        #     fields=[
        #         ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='行程id')),
        #         ('user_id', models.CharField(blank=True, max_length=50, verbose_name='app用户id')),
        #         ('car_name', models.CharField(max_length=100, verbose_name='车型名')),
        #         ('file_name', models.CharField(blank=True, max_length=500, verbose_name='行程文件名')),
        #         ('is_completed', models.BooleanField(default=False, verbose_name='行程是否已完成合并')),
        #         ('is_merging', models.BooleanField(default=False, verbose_name='行程正在合并中')),
        #         ('first_update', models.DateTimeField(auto_now_add=True, verbose_name='行程第一次分片接收时间')),
        #         ('last_update', models.DateTimeField(auto_now=True, verbose_name='行程最后一次分片接收时间')),
        #         ('merged_csv_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='行程合并csv文件路径')),
        #         ('merged_det_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='行程合并det文件路径')),
        #         ('hardware_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='行程硬件版本')),
        #         ('software_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='行程软件版本')),
        #         ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='行程生成设备id')),
        #         ('merge_into_current', models.BooleanField(default=True, verbose_name='异常行程合并到当前行程')),
        #         ('set_journey_status', models.BooleanField(default=False, verbose_name='异常行程是否已设置行程状态')),
        #         ('trip_status', models.CharField(blank=True, max_length=50, verbose_name='行程状态')),
        #         ('reported_car_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='上报模式车型名')),
        #         ('reported_hardware_version', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='上报模式行程硬件版本')),
        #         ('reported_software_version', models.CharField(blank=True, max_length=64, null=True, verbose_name='上报模式行程软件版本')),
        #         ('parent_trip_id', models.UUIDField(blank=True, help_text='如果是子行程，则指向父行程的ID', null=True, verbose_name='父行程ID')),
        #         ('record_upload_tos_status', models.CharField(default=False, max_length=50, verbose_name='行程音频文件落库状态')),
        #         ('record_audio_file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='行程音频文件路径')),
        #         ('csv_chunk_count', models.IntegerField(default=0, verbose_name='行程csv分片数量')),
        #         ('csv_chunk_lose', models.IntegerField(default=0, verbose_name='行程csv分片丢失数量')),
        #         ('det_chunk_count', models.IntegerField(default=0, verbose_name='行程det分片数量')),
        #         ('det_chunk_lose', models.IntegerField(default=0, verbose_name='行程det分片丢失数量')),
        #     ],
        #     options={
        #         'db_table': 'trip',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='analysis_data_app',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
        #         ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        #         ('model', models.CharField(editable=False, max_length=255, null=True, verbose_name='用户使用车型')),
        #         ('intervention', models.IntegerField(blank=True, default=0, null=True, verbose_name='接管次数')),
        #         ('intervention_risk', models.IntegerField(blank=True, default=0, null=True, verbose_name='危险接管次数')),
        #         ('mpi', models.FloatField(blank=True, default=0.0, null=True, verbose_name='接管里程')),
        #         ('mpi_risk', models.FloatField(blank=True, default=0.0, null=True, verbose_name='危险接管里程')),
        #         ('total_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='总里程')),
        #         ('noa_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA总里程')),
        #         ('lcc_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='LCC总里程')),
        #         ('noa_lcc_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA LCC总里程')),
        #         ('standby_mile', models.FloatField(blank=True, default=0.0, null=True, verbose_name='人类驾驶里程')),
        #         ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'db_table': 'analysis_data_app',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='tos_csv_app',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
        #         ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
        #         ('tos_file_path', models.CharField(editable=False, max_length=2000, verbose_name='tos存储路径')),
        #         ('tos_file_type', models.CharField(editable=False, max_length=2000, verbose_name='tos存储文件类型 inference/analysis')),
        #         ('approved_status', models.IntegerField(default=0, verbose_name='审核状态：0 未审核， 1 审核通过 2 审核不通过')),
        #         ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'db_table': 'tos_csv_app',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='RecoredChunkFile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('chunk_index', models.IntegerField()),
        #         ('file_path', models.CharField(max_length=255)),
        #         ('file_type', models.CharField(max_length=10)),
        #         ('file_name', models.CharField(blank=True, max_length=500)),
        #         ('upload_time', models.DateTimeField(auto_now_add=True)),
        #         ('car_name', models.CharField(max_length=100)),
        #         ('hardware_version', models.CharField(blank=True, max_length=64, null=True)),
        #         ('software_version', models.CharField(blank=True, max_length=64, null=True)),
        #         ('device_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recored_chunks', to='common_task.trip')),
        #     ],
        #     options={
        #         'db_table': 'RecoredChunkFile',
        #         'unique_together': {('trip', 'chunk_index', 'file_type')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ChunkFile',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('chunk_index', models.IntegerField()),
        #         ('file_path', models.CharField(max_length=255)),
        #         ('file_type', models.CharField(max_length=10)),
        #         ('file_name', models.CharField(blank=True, max_length=500)),
        #         ('upload_time', models.DateTimeField(auto_now_add=True)),
        #         ('car_name', models.CharField(max_length=100)),
        #         ('hardware_version', models.CharField(blank=True, max_length=64, null=True)),
        #         ('software_version', models.CharField(blank=True, max_length=64, null=True)),
        #         ('device_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='common_task.trip')),
        #     ],
        #     options={
        #         'db_table': 'chunkfile',
        #         'unique_together': {('trip', 'chunk_index', 'file_type')},
        #     },
        # ),
            migrations.RunSQL(
            sql="SELECT 1",  # 不执行任何操作的 SQL
            reverse_sql="SELECT 1",
        ),
    ]
