# Generated by Django 5.1.7 on 2025-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='trip',
            name='file_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
