# Generated by Django 5.0.6 on 2024-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0002_analysis_data_app_cur_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_data_app',
            name='cur_speed',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='当前速度'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='intervention',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='接管次数'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='intervention_risk',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='危险接管次数'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='intervention_state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='当前帧接管状态'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='lcc_mile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='LCC总里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='mpi',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='接管里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='mpi_risk',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='危险接管里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='noa_lcc_mile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA LCC总里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='noa_mile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='NOA总里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='standby_mile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='人类驾驶里程'),
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='total_mile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='总里程'),
        ),
    ]
