# Generated by Django 5.0.6 on 2024-07-15 07:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0003_alter_analysis_data_app_cur_speed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis_data_app',
            name='cur_speed',
        ),
        migrations.RemoveField(
            model_name='analysis_data_app',
            name='intervention_state',
        ),
        migrations.AddField(
            model_name='analysis_data_app',
            name='model',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='用户使用车型'),
        ),
        migrations.AddField(
            model_name='analysis_data_app',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis_data_app',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='tos_csv_app',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tos_file_path', models.CharField(editable=False, max_length=2000, verbose_name='tos存储路径')),
                ('tos_file_type', models.CharField(editable=False, max_length=2000, verbose_name='tos存储文件类型 inference/analysis')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tos_csv_app',
            },
        ),
    ]
