# Generated by Django 5.0.6 on 2024-07-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0004_remove_analysis_data_app_cur_speed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis_data_app',
            old_name='user_id',
            new_name='user',
        ),
    ]
