# Generated by Django 5.0.6 on 2024-07-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0005_rename_user_id_analysis_data_app_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tos_csv_app',
            old_name='user_id',
            new_name='user',
        ),
    ]
