# Generated by Django 5.1.6 on 2025-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0006_rename_user_id_tos_csv_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tos_csv_app',
            name='approved_status',
            field=models.IntegerField(default=0, verbose_name='审核状态：0 未审核， 1 审核通过 2 审核不通过'),
        ),
    ]
