# Generated by Django 5.1.7 on 2025-03-27 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0007_tos_csv_app_approved_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='行程ID')),
                ('device_id', models.CharField(max_length=50, verbose_name='设备ID')),
                ('car_name', models.CharField(max_length=50, verbose_name='车辆名称')),
                ('start_time', models.BigIntegerField(verbose_name='开始时间')),
                ('end_time', models.BigIntegerField(null=True, verbose_name='结束时间')),
                ('total_chunks', models.IntegerField(default=0, verbose_name='总块数')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merged_csv_path', models.CharField(blank=True, max_length=255, null=True)),
                ('merged_det_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChunkFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='唯一标识ID')),
                ('chunk_index', models.IntegerField(verbose_name='块ID')),
                ('file_type', models.CharField(max_length=10, verbose_name='文件类型')),
                ('start_time', models.BigIntegerField(verbose_name='开始时间')),
                ('end_time', models.BigIntegerField(verbose_name='结束时间')),
                ('checksum', models.CharField(max_length=64, verbose_name='校验和')),
                ('file_path', models.CharField(max_length=2000, verbose_name='文件路径')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否处理')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_task.trip', verbose_name='行程')),
            ],
        ),
    ]
