# Generated by Django 5.1.7 on 2025-03-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0008_trip_chunkfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='device_id',
            field=models.CharField(max_length=255, verbose_name='设备ID'),
        ),
    ]
