# Generated by Django 5.1.7 on 2025-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_task', '0009_alter_trip_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkfile',
            name='end_time',
            field=models.BigIntegerField(null=True, verbose_name='结束时间'),
        ),
    ]
