apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-gateway-saas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/backend-gateway-saas.git
    targetRevision: main
    path: charts/backend-gateway-saas
    helm:
      releaseName: backend-gateway-saas
      parameters:
        - name: image.registry
          value: chek-images-cn-beijing.cr.volces.com
        - name: image.repository
          value: prod/backend-gateway-saas
        - name: image.tag
          value: sha-24bd0dd
        - name: service.type
          value: NodePort
        - name: service.port
          value: "80"
        - name: service.targetPort
          value: "12000"
        - name: containerPort
          value: "12000"
        - name: envFromSecret
          value: nacos-cred-gateway
        - name: env.NACOS_HOST
          value: "172.31.120.5"
        - name: env.NACOS_PORT
          value: "8848"
        - name: env.SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR
          value: "172.31.120.5:8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          value: "172.31.120.5:8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
          value: "a15810b5-cca6-4eb2-9f6d-7a2c0d68fa76"
        - name: env.SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
          value: "a15810b5-cca6-4eb2-9f6d-7a2c0d68fa76"
        - name: env.SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration"
        - name: env.MANAGEMENT_HEALTH_DB_ENABLED
          value: "false"
        - name: env.MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: env.MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: env.SPRING_CLOUD_DISCOVERY_CLIENT_HEALTH_INDICATOR_ENABLED
          value: "false"
        - name: env.SPRING_PROFILES_ACTIVE
          value: "no-db"
        - name: env.SECURE_IGNORE_URLS
          value: "/api/offline/diag/**,/api/offline/docs,/api/offline/openapi.json,/openapi.json,/actuator/**,/api/osmgw/actuator/**,/api/osmgw/metrics,/api/osmgw/healthz,/api/vms/healthz,/api/vms/actuator/**"
        - name: env.SPRING_APPLICATION_JSON
          value: |
            {
              "secure": {
                "ignore": {
                  "urls": [
                    "/auth/v1/getClientToken",
                    "/actuator/**",
                    "/api/offline/diag/**",
                    "/api/offline/docs",
                    "/api/offline/openapi.json",
                    "/openapi.json",
                    "/api/offline/healthz",
                    "/api/osmgw/actuator/**",
                    "/api/osmgw/metrics",
                    "/api/osmgw/healthz","/api/vms/healthz","/api/vms/actuator/**"
                  ]
                }
              },
              "spring": {
                "cloud": {
                  "gateway": {
                    "routes": [
                      {
                        "id": "offline-openapi-root",
                        "uri": "http://backend-miker-offline.miker-prod.svc.cluster.local:80",
                        "predicates": ["Path=/openapi.json"],
                        "filters": ["SetPath=/api/offline/openapi.json"]
                      },
                      {
                        "id": "vehicle-model-service",
                        "uri": "http://vehicle-model-service.miker-prod.svc.cluster.local:8080",
                        "predicates": ["Path=/api/vms/**"],
                        "filters": ["StripPrefix=2"]
                      }
                    ]
                  }
                }
              }
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: miker-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

