apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-gateway-saas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/backend-gateway-saas.git
    targetRevision: main
    path: charts/backend-gateway-saas
    helm:
      valueFiles:
        - values-prod.yaml
      releaseName: backend-gateway-saas
      parameters:
        - name: image.registry
          value: chek-images-cn-beijing.cr.volces.com
        - name: image.repository
          value: prod/backend-gateway-saas
        - name: image.tag
          value: sha-24bd0dd
        - name: service.type
          value: NodePort
        - name: service.port
          value: "80"
        - name: service.targetPort
          value: "12000"
        - name: containerPort
          value: "12000"
        - name: envFromSecret
          value: nacos-cred-gateway
        - name: env.NACOS_HOST
          value: "172.31.120.5"
        - name: env.NACOS_PORT
          value: "8848"
        - name: env.SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR
          value: "172.31.120.5:8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR
          value: "172.31.120.5:8848"
        - name: env.SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
          value: "a15810b5-cca6-4eb2-9f6d-7a2c0d68fa76"
        - name: env.SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
          value: "a15810b5-cca6-4eb2-9f6d-7a2c0d68fa76"
        - name: env.SPRING_AUTOCONFIGURE_EXCLUDE
          value: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure,org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration"
        - name: env.MANAGEMENT_HEALTH_DB_ENABLED
          value: "false"
        - name: env.MANAGEMENT_HEALTH_REDIS_ENABLED
          value: "false"
        - name: env.MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: env.SPRING_CLOUD_DISCOVERY_CLIENT_HEALTH_INDICATOR_ENABLED
          value: "false"
        - name: env.SPRING_PROFILES_ACTIVE
          value: "no-db"
        - P25-11-14T05:48:28Z"
        - name: env.SPRING_CLOUD_NACOS_CONFIG_ENABLED
          value: "false"
        # Gateway routes: offline openapi under prefix
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_0_ID
          value: offline-openapi-prefixed
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          value: http://backend-miker-offline.miker-prod.svc.cluster.local:80
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
          value: Path=/api/offline/openapi.json
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
          value: SetPath=/openapi.json
        # Gateway routes: vms service
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_1_ID
          value: vehicle-model-service
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_1_URI
          value: http://vehicle-model-service.miker-prod.svc.cluster.local:8080
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
          value: Path=/api/vms/**
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
          value: StripPrefix=2
        # Gateway routes: osm-gateway (business, keep prefix)
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_2_ID
          value: osm-gateway-biz
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_2_URI
          value: http://osm-gateway.miker-prod.svc.cluster.local:80
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
          value: Path=/api/osm-gateway/**
        # Gateway routes: osm-gateway OpenAPI rewrite
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_3_ID
          value: osm-gateway-openapi
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_3_URI
          value: http://osm-gateway.miker-prod.svc.cluster.local:80
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0
          value: Path=/api/osm-gateway/openapi.json
        - name: env.SPRING_CLOUD_GATEWAY_ROUTES_3_FILTERS_0
          value: SetPath=/openapi.json
        # Security whitelist
        - name: env.SECURE_IGNORE_URLS
          value: /api/offline/openapi.json,/openapi.json,/openapi,/actuator/**,/api/vms/healthz,/api/vms/actuator/**,/api/osm-gateway/healthz,/api/osm-gateway/actuator/**,/api/osm-gateway/openapi.json
  destination:
    server: https://kubernetes.default.svc
    namespace: miker-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

