apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/backend-app.git
    targetRevision: main
    path: charts/backend-app
    helm:
      releaseName: backend-app
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.registry
          value: chek-images-cn-beijing.cr.volces.com
        - name: image.repository
          value: prod/backend-app
        - name: image.tag
          value: v0.1.0
        - name: service.type
          value: ClusterIP
        - name: service.port
          value: "80"
        - name: service.targetPort
          value: "8000"
        - name: containerPort
          value: "8000"
        # Disable Ingress in backend-app chart to avoid抢占 api.chekkk.com 根路径
        - name: ingress.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



