apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-saas-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@ssh.github.com:443/chekdata/ops-bootstrap.git
    targetRevision: main
    path: charts/frontend-saas
    helm:
      valueFiles:
        - values.prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



